### ISSUE TITLE
A question about 'cifarpoison.pt' pretrained model in models folder

### ISSUE THREAD

**Issue by BeStrongok** [wangren09/TrojanNetDetector#1]
- Hello, when i reproduced DFTND experiment, i wanna kown the performence of your pretrained model "cifarpoison.pt" on cifar10 poisoned dataset, so i use your code in 'train_model.ipynb' to load the model in 'models' folder and test it's nature acc and poison acc, but i get this result:
pattern -1 4 [26, 26] [255, 0, 0]
  natural: 82.20%
  avg nat xent: 0.0011
  poisoned: 7.46%
  avg pois xent: 0.0252

- Under the same operation, the 'cifarpertclean.pt'  is:
pattern -1 4 [26, 26] [255, 0, 0]
  natural: 81.07%
  avg nat xent: 0.0011
  poisoned: 9.27%
  avg pois xent: 0.0171

- And i use your code in 'train_model.ipynb' to train my own model 'cifarpert.pt', then do the same operation, the result is: pattern -1 4 [26, 26] [255, 0, 0]
  natural: 80.75%
  avg nat xent: 0.0011
  poisoned: 100.00%
  avg pois xent: 0.0000

- So, i think the code i use to load and test is correct, the pretrained model 'cifarpoison.pt' may have problem, because it's poison acc is very low, and this may lead an uncorrect result about the trojan detection , can you help me solve this probelm? Thank you very much!

**Comment by wangren09** [comment]
Hi @BeStrongok , sorry for the late reply. The trigger used on the poisoned model has a different location. Please replace [26,26] with [29,29], and you should see the poisoned rate up to 99.99%. Hope that answer your question.

**Comment by BeStrongok** [comment]
Thank you for your reply, your answer solved my question. But i have another question, i use a different trigger and a different location to train my own poisoned model, and use your dftnd code to detect, but it cannot detect the model as poisoned model.
I think my training code has no problem, does the dftnd algorithem has any limitation?

**Comment by wangren09** [comment]
Hi, I am not sure about the reason since I don't have the model info. But the performance of the detector may vary when the poisoning rate changes. And depending on the sparsity, the penalty parameter (gamma) might also affect. I would suggest you vary the penalty parameter and see how the trigger reverse engineering perform.

**Comment by BeStrongok** [comment]
Thank you! I will try it. :）
